import type { Circle, Work } from "@/lib/types";

export const DEMO_CIRCLE: Circle = {
  id: "maru-maru",
  name: "◯◯製作所",
  initial: "◯",
  description: "お姉さん系・甘やかし・寝落としが中心。漫画と音声の両方を展開。",
  workCount: 41,
  latestDate: "2026/06/08",
  avgPrice: 980,
  mangaCount: 18,
  cgCount: 9,
  voiceCount: 8,
  gameCount: 1,
  tags: ["年上", "耳舐め", "寝落とし", "囁き"],
};

export const DEMO_WORKS: Work[] = [
  {
    id: "voice-001",
    title: "甘やかしお姉さんの寝落としボイス",
    mediaType: "voice",
    price: 1320,
    duration: "45分",
    date: "2026/06/08",
    tags: ["年上", "寝落とし", "耳舐め"],
    circleId: "maru-maru",
    circleName: "◯◯製作所",
  },
  {
    id: "voice-002",
    title: "雨の日のお姉さんと",
    mediaType: "voice",
    price: 1100,
    duration: "38分",
    date: "2026/05/20",
    tags: ["囁き"],
    circleId: "maru-maru",
    circleName: "◯◯製作所",
  },
  {
    id: "manga-001",
    title: "同僚お姉さん 残業編",
    mediaType: "manga",
    price: 880,
    pages: 32,
    date: "2026/05/01",
    tags: ["シリーズ2"],
    circleId: "maru-maru",
    circleName: "◯◯製作所",
  },
  {
    id: "cg-001",
    title: "お姉さんイラスト集 Vol.3",
    mediaType: "cg",
    price: 770,
    pages: 48,
    date: "2026/04/10",
    tags: ["制服"],
    circleId: "maru-maru",
    circleName: "◯◯製作所",
  },
  {
    id: "voice-003",
    title: "年上彼女の甘い囁き",
    mediaType: "voice",
    price: 990,
    duration: "52分",
    date: "2026/03/15",
    tags: ["年上"],
    circleId: "maru-maru",
    circleName: "◯◯製作所",
  },
  {
    id: "manga-002",
    title: "同僚お姉さん 初回出会い編",
    mediaType: "manga",
    price: 880,
    pages: 28,
    date: "2026/02/01",
    tags: ["シリーズ1"],
    circleId: "maru-maru",
    circleName: "◯◯製作所",
  },
  {
    id: "game-001",
    title: "お姉さんと過ごす休日",
    mediaType: "game",
    price: 1650,
    date: "2026/01/20",
    tags: ["ノベル"],
    circleId: "maru-maru",
    circleName: "◯◯製作所",
  },
  {
    id: "voice-004",
    title: "添い寝ボイス 〜静かな夜〜",
    mediaType: "voice",
    price: 880,
    duration: "60分",
    date: "2025/11/18",
    tags: ["寝落とし"],
    circleId: "maru-maru",
    circleName: "◯◯製作所",
  },
];

export const FEATURED_WORK = DEMO_WORKS[0];
